FROM golang:1.17.10-stretch
ENV GO111MODULE=on GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
# RUN mkdir -p $GOPATH/src/golang.org/x/
# RUN cd $GOPATH/src/golang.org/x/ && git clone https://github.com/golang/net.git
# RUN cd $GOPATH/src/golang.org/x/ &&  git clone https://github.com/golang/sys.git
# RUN go get github.com/awesome-fc/golang-runtime
# RUN go get github.com/gorilla/websocket
